services:
  ome:
    image: irth7/ovenmediaengine:v0.14.18
    ports:
      - 1935:1935
      - 3478:3478
      - 10000-10005:10000-10005/udp
    volumes:
      - ./data/ome:/opt/ovenmediaengine/bin/origin_conf
      - ./ome_conf/Server.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml:ro
    environment:
      - OME_API_TOKEN=papiez

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/frontend/dist:/usr/share/nginx/html
    ports:
      - 6213:80
    depends_on:
      - web
      - ome

  web:
    build: ./web
    volumes:
      - ./data/web:/data
      - ./web/frontend/dist:/static
